### PR TITLE
Fix issue with s390x support on sensor API

### LINKED ISSUE #65: Broken responses from sensor installer API due to s390x support
A recent introduction to the sensor installer API query results in broken responses due to existing code not accounting for s390x.

### PR DESCRIPTION
**Pull request by carlosmmatos**
Fixes #65 

This PR fixes an issue introduced by our sensor installer API that deals with supporting a new s390x architecture for the falcon sensor.

### CODE REVIEW

**Review by ffalor — APPROVED** [review]

File: lib/puppet/puppet_x/helper.rb [hunk 1]
```diff
@@ -12,10 +12,15 @@ def build_sensor_installer_query(platform_name:, os_name: nil, version: nil, os_
   end
 
   unless architecture.nil?
-    query += if architecture.casecmp('arm64').zero?
```
Comment (ffalor) [inline lib/puppet/puppet_x/helper.rb:15]:
```
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, Unsupported architecture: amd64 (file: /github/workspace/spec/fixtures/modules/falcon/manifests/install.pp, line: 23, column: 15) on node 9a06a9366edc.mma5zatft5wupo5mzspaixdheh.bx.internal.cloudapp.net
     # ./spec/fixtures/modules/falcon/lib/puppet/puppet_x/helper.rb:23:in `build_sensor_installer_query'
     # ./spec/fixtures/modules/falcon/lib/puppet/functions/falcon/sensor_download_info.rb:58:in `sensor_download_info'
     # ./spec/classes/falcon_spec.rb:162:in `block (6 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Puppet::Error:
     #   Unsupported architecture: amd64
     #   ./spec/fixtures/modules/falcon/lib/puppet/puppet_x/helper.rb:23:in `build_sensor_installer_query'
     ```
